# Generated by Django 4.1.5 on 2023-01-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_brand_products_delete_marca_delete_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
